FROM docker:23.0.1-cli-alpine3.17

VOLUME /opt/planets
WORKDIR /opt/planets
ENV shell_profile=/etc/profile

RUN set -eux; apk add --no-cache ca-certificates git jq bash make coreutils;
RUN wget -q -O - https://git.io/vQhTU | bash -s -- --version 1.20.1

ARG UID=1000
ARG GID=1000
USER ${UID}:${GID}

ENTRYPOINT [ "/bin/bash" ]