---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - cosmos.nebula-labs.org
  resources:
  - nets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cosmos.nebula-labs.org
  resources:
  - nets/finalizers
  verbs:
  - update
- apiGroups:
  - cosmos.nebula-labs.org
  resources:
  - nets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cosmos.nebula-labs.org
  resources:
  - nodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cosmos.nebula-labs.org
  resources:
  - nodes/finalizers
  verbs:
  - update
- apiGroups:
  - cosmos.nebula-labs.org
  resources:
  - nodes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cosmos.nebula-labs.org
  resources:
  - relayers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cosmos.nebula-labs.org
  resources:
  - relayers/finalizers
  verbs:
  - update
- apiGroups:
  - cosmos.nebula-labs.org
  resources:
  - relayers/status
  verbs:
  - get
  - patch
  - update
