## Append samples you want in your CSV to this file as resources ##
resources:
- cosmos_v1alpha1_node.yaml
- cosmos_v1alpha1_net.yaml
- cosmos_v1alpha1_relayer.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
